package omnimesh.command1.ui

import androidx.compose.animation.AnimatedVisibility
import androidx.compose.animation.fadeOut
import androidx.compose.animation.core.RepeatMode
import androidx.compose.animation.core.Animatable
import androidx.compose.animation.core.animateFloat
import androidx.compose.animation.core.animateIntAsState
import androidx.compose.animation.core.infiniteRepeatable
import androidx.compose.animation.core.rememberInfiniteTransition
import androidx.compose.animation.core.tween
import androidx.compose.animation.fadeIn
import androidx.compose.animation.slideInVertically
import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.ExperimentalFoundationApi
import androidx.compose.foundation.background
import androidx.compose.foundation.basicMarquee
import androidx.compose.foundation.border
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.clickable
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxHeight
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.heightIn
import androidx.compose.foundation.layout.navigationBarsPadding
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.graphicsLayer
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.Path
import androidx.compose.ui.graphics.Shadow
import androidx.compose.ui.platform.LocalDensity
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.geometry.Size
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import kotlinx.coroutines.delay
import omnimesh.command1.command.SpikeAlert
import omnimesh.command1.data.TriagePacket
import omnimesh.command1.ml.DispatchAgent
import omnimesh.command1.ui.components.CommandMeshVisualization
import omnimesh.command1.ui.components.MeshBackground
import omnimesh.command1.ui.components.OmniMeshTopBar
import omnimesh.command1.ui.theme.GoogleSans
import omnimesh.command1.ui.theme.OmniMeshColors
import omnimesh.command1.ui.theme.urgencyColor
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import kotlin.math.abs
import kotlin.math.cos
import kotlin.math.sin

@Composable
fun CommandScreen(
    viewModel: OmniMeshViewModel,
    packets: List<TriagePacket>,
    dispatchResult: DispatchAgent.DispatchRecommendation?,
    demoMode: Boolean,
    onToggleDemoMode: () -> Unit,
    onRunAgent: () -> Unit,
    onSpeakDispatch: (String) -> Unit
) {
    val scroll = rememberScrollState()
    val redCount = packets.count { it.urgency == "RED" }
    val autoCount = packets.count { it.isAutoGenerated }
    val peerCount by viewModel.peerCount.collectAsState()

    // Live clock for the header — re-emits every second on a single composable.
    var clockTick by remember { mutableStateOf(System.currentTimeMillis()) }
    LaunchedEffect(Unit) {
        while (true) {
            clockTick = System.currentTimeMillis()
            delay(1000)
        }
    }

    var analyzing by remember { mutableStateOf(false) }
    var showTimeline by remember { mutableStateOf(false) }
    val timelineEvents by viewModel.timelineEvents.collectAsState(initial = emptyList())
    val spikeAlert by viewModel.spikeAlert.collectAsState()
    val metricHistory by viewModel.commandMetricHistory.collectAsState()
    val analysisText = dispatchResult?.rawAnalysis.orEmpty()
    LaunchedEffect(dispatchResult) {
        if (dispatchResult != null) analyzing = false
    }
    LaunchedEffect(packets.size, redCount, autoCount) {
        viewModel.pushCommandMetricSnapshot(
            total = packets.size,
            critical = redCount,
            autoSos = autoCount
        )
    }

    Box(modifier = Modifier.fillMaxSize()) {
        MeshBackground(
            modifier = Modifier.fillMaxSize(),
            nodeCount = 40,
            nodeColor = Color(0xFF174EA6),
            edgeColor = Color(0xFF4285F4),
            nodeAlpha = 0.14f,
            edgeAlpha = 0.06f,
        )
        Column(
            modifier = Modifier
                .fillMaxSize()
                .background(OmniMeshColors.DarkBackground.copy(alpha = 0.88f))
        ) {
            OmniMeshTopBar(
                screenName = "COMMAND",
                peerCount = peerCount,
                showTimezone = true,
            )
            Column(
                modifier = Modifier
                    .weight(1f)
                    .fillMaxWidth()
                    .verticalScroll(scroll)
                    .navigationBarsPadding()
                    .padding(horizontal = 16.dp)
                    .padding(top = 16.dp, bottom = 24.dp),
                verticalArrangement = Arrangement.spacedBy(16.dp)
            ) {

        CommandHeader(now = clockTick)

        StatRow(
            total = packets.size,
            critical = redCount,
            autoSos = autoCount,
            totalHistory = metricHistory["TOTAL"].orEmpty(),
            criticalHistory = metricHistory["CRITICAL"].orEmpty(),
            autoHistory = metricHistory["AUTO-SOS"].orEmpty()
        )

        AnimatedVisibility(visible = autoCount >= 3) {
            CollapseProtocolBanner(autoCount = autoCount)
        }
        SpikeAlertBanner(spikeAlert = spikeAlert, onDismiss = viewModel::dismissSpikeAlert)

        CommandMeshVisualization(
            activePeers = peerCount,
            criticalCount = redCount,
            modifier = Modifier
                .fillMaxWidth()
                .height(280.dp)
        )

        OnDeviceCollapseVerificationStrip()

        GeminiTerminalPanel(
            analysisText = analysisText,
            hasResult = dispatchResult != null,
            estimatedCasualties = dispatchResult?.estimatedCasualties,
            analyzing = analyzing,
            packetCount = packets.size,
            onRun = {
                analyzing = true
                onRunAgent()
            },
            onSpeak = onSpeakDispatch
        )

        if (dispatchResult?.zoneAssignments?.isNotEmpty() == true) {
            ZoneAssignments(zoneAssignments = dispatchResult.zoneAssignments)
        }

        dispatchResult?.criticalAlert?.let { CriticalAlertBox(it) }
        PacketTable(packets = packets)
        Row(
            modifier = Modifier
                .fillMaxWidth()
                .clickable { showTimeline = !showTimeline }
                .padding(vertical = 12.dp),
            horizontalArrangement = Arrangement.SpaceBetween,
            verticalAlignment = Alignment.CenterVertically
        ) {
            Text(
                "INCIDENT TIMELINE",
                color = Color(0xFF9AA0A6),
                fontSize = 12.sp,
                fontFamily = FontFamily.Monospace,
                fontWeight = FontWeight.Bold,
                letterSpacing = 1.sp
            )
            Text(
                if (showTimeline) "▲ HIDE" else "▼ SHOW (${timelineEvents.size})",
                color = Color(0xFF4285F4),
                fontSize = 11.sp,
                fontFamily = FontFamily.Monospace,
                fontWeight = FontWeight.Bold
            )
        }
        AnimatedVisibility(visible = showTimeline) {
            IncidentTimelineView(
                events = timelineEvents,
                modifier = Modifier
                    .fillMaxWidth()
                    .height(400.dp)
                    .background(Color(0xFF0D1117), RoundedCornerShape(8.dp))
            )
        }
            }
        }
    }
}

@Composable
private fun SpikeAlertBanner(spikeAlert: SpikeAlert?, onDismiss: () -> Unit) {
    AnimatedVisibility(visible = spikeAlert != null) {
        spikeAlert?.let { alert ->
            Row(
                modifier = Modifier
                    .fillMaxWidth()
                    .background(Color(0xFFEA4335).copy(alpha = 0.08f))
                    .border(1.dp, Color(0xFFEA4335).copy(alpha = 0.4f))
                    .padding(12.dp),
                horizontalArrangement = Arrangement.SpaceBetween,
                verticalAlignment = Alignment.CenterVertically
            ) {
                Column(modifier = Modifier.weight(1f)) {
                    Text(
                        "📈 ACTIVITY SPIKE DETECTED",
                        color = Color(0xFFEA4335),
                        fontSize = 11.sp,
                        fontFamily = FontFamily.Monospace,
                        fontWeight = FontWeight.Bold,
                        letterSpacing = 1.sp
                    )
                    Text(alert.message, color = Color(0xFF9AA0A6), fontSize = 12.sp)
                }
                Text(
                    "Dismiss",
                    color = Color(0xFF9AA0A6),
                    fontSize = 11.sp,
                    fontFamily = FontFamily.Monospace,
                    modifier = Modifier.clickable { onDismiss() }.padding(8.dp)
                )
            }
        }
    }
}

@Composable
private fun OnDeviceCollapseVerificationStrip() {
    var expanded by remember { mutableStateOf(false) }
    val transition = rememberInfiniteTransition(label = "cmd-ondevice")
    val phase by transition.animateFloat(
        initialValue = 0f,
        targetValue = (Math.PI * 2).toFloat(),
        animationSpec = infiniteRepeatable(animation = tween(1200), repeatMode = RepeatMode.Restart),
        label = "phase"
    )
    val pulse by transition.animateFloat(
        initialValue = 0.45f,
        targetValue = 1f,
        animationSpec = infiniteRepeatable(animation = tween(900), repeatMode = RepeatMode.Reverse),
        label = "pulse"
    )

    Surface(
        modifier = Modifier.fillMaxWidth(),
        shape = RoundedCornerShape(10.dp),
        color = OmniMeshColors.DarkSurface,
        border = BorderStroke(1.dp, OmniMeshColors.MediumBlue.copy(alpha = 0.35f))
    ) {
        Column(modifier = Modifier.padding(horizontal = 12.dp, vertical = 10.dp)) {
            Row(
                modifier = Modifier
                    .fillMaxWidth()
                    .clickable { expanded = !expanded },
                horizontalArrangement = Arrangement.SpaceBetween,
                verticalAlignment = Alignment.CenterVertically
            ) {
                Text(
                    text = "ON-DEVICE AI ANALYSIS · COLLAPSE VERIFICATION",
                    color = OmniMeshColors.White,
                    fontSize = 10.sp,
                    letterSpacing = 1.2.sp,
                    fontWeight = FontWeight.Bold,
                    fontFamily = GoogleSans
                )
                Text(
                    text = if (expanded) "▲ HIDE" else "▼ SHOW",
                    color = OmniMeshColors.MediumBlue,
                    fontSize = 10.sp,
                    fontFamily = FontFamily.Monospace,
                    fontWeight = FontWeight.Bold
                )
            }
            AnimatedVisibility(visible = expanded) {
                Column {
                    Spacer(Modifier.height(8.dp))
                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.spacedBy(10.dp)
                    ) {
                        Surface(
                            modifier = Modifier.weight(1f),
                            shape = RoundedCornerShape(8.dp),
                            color = OmniMeshColors.DarkBackground,
                            border = BorderStroke(1.dp, OmniMeshColors.MediumRed.copy(alpha = 0.35f))
                        ) {
                            Column(modifier = Modifier.padding(8.dp)) {
                                Text("ACOUSTIC", color = OmniMeshColors.MediumRed, fontSize = 10.sp, fontFamily = FontFamily.Monospace, fontWeight = FontWeight.Bold, letterSpacing = 1.sp)
                                Spacer(Modifier.height(4.dp))
                                Canvas(modifier = Modifier.fillMaxWidth().height(24.dp)) {
                                    val bars = 8
                                    val gap = size.width / (bars * 2f)
                                    val w = gap
                                    repeat(bars) { i ->
                                        val amp = (0.3f + 0.7f * abs(sin(phase + i * 0.7f))).toFloat()
                                        val h = size.height * amp
                                        val x = i * (w + gap) + gap * 0.5f
                                        drawRect(
                                            color = OmniMeshColors.MediumRed.copy(alpha = 0.85f),
                                            topLeft = androidx.compose.ui.geometry.Offset(x, size.height - h),
                                            size = androidx.compose.ui.geometry.Size(w, h)
                                        )
                                    }
                                }
                            }
                        }
                        Surface(
                            modifier = Modifier.weight(1f),
                            shape = RoundedCornerShape(8.dp),
                            color = OmniMeshColors.DarkBackground,
                            border = BorderStroke(1.dp, OmniMeshColors.Yellow.copy(alpha = 0.35f))
                        ) {
                            Column(modifier = Modifier.padding(8.dp), verticalArrangement = Arrangement.spacedBy(3.dp)) {
                                Text("MOTION", color = OmniMeshColors.Yellow.copy(alpha = pulse), fontSize = 10.sp, fontFamily = FontFamily.Monospace, fontWeight = FontWeight.Bold, letterSpacing = 1.sp)
                                Text("Abnormal impact profile detected", color = OmniMeshColors.White.copy(alpha = 0.9f), fontSize = 11.sp, fontFamily = GoogleSans)
                                Text("Sensor fusion confidence rising", color = OmniMeshColors.Grey, fontSize = 10.sp, fontFamily = GoogleSans)
                            }
                        }
                        Surface(
                            modifier = Modifier.weight(1f),
                            shape = RoundedCornerShape(8.dp),
                            color = OmniMeshColors.DarkBackground,
                            border = BorderStroke(1.dp, OmniMeshColors.MediumBlue.copy(alpha = 0.35f))
                        ) {
                            Column(modifier = Modifier.padding(8.dp)) {
                                Text("STRUCTURAL", color = OmniMeshColors.MediumBlue, fontSize = 10.sp, fontFamily = FontFamily.Monospace, fontWeight = FontWeight.Bold, letterSpacing = 1.sp)
                                Spacer(Modifier.height(4.dp))
                                Canvas(modifier = Modifier.fillMaxWidth().height(24.dp)) {
                                    val edge = OmniMeshColors.MediumBlue.copy(alpha = 0.7f)
                                    drawLine(edge, androidx.compose.ui.geometry.Offset(size.width * 0.08f, size.height * 0.82f), androidx.compose.ui.geometry.Offset(size.width * 0.35f, size.height * 0.25f), 1.8f)
                                    drawLine(edge, androidx.compose.ui.geometry.Offset(size.width * 0.35f, size.height * 0.25f), androidx.compose.ui.geometry.Offset(size.width * 0.6f, size.height * 0.72f), 1.8f)
                                    drawLine(edge, androidx.compose.ui.geometry.Offset(size.width * 0.6f, size.height * 0.72f), androidx.compose.ui.geometry.Offset(size.width * 0.9f, size.height * 0.35f), 1.8f)
                                    drawRect(
                                        color = OmniMeshColors.MediumGreen.copy(alpha = 0.5f),
                                        topLeft = androidx.compose.ui.geometry.Offset(0f, size.height * ((phase / (Math.PI.toFloat() * 2f)) % 1f)),
                                        size = androidx.compose.ui.geometry.Size(size.width, 1.8f)
                                    )
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Header
// ─────────────────────────────────────────────────────────────────────────────

@Composable
private fun CommandHeader(now: Long) {
    val timeDf = remember { SimpleDateFormat("HH:mm:ss", Locale.getDefault()) }
    val zoneDf = remember { SimpleDateFormat("z XXX", Locale.getDefault()) }
    Column {
        Text(
            text = "COMMAND CENTER",
            color = OmniMeshColors.White,
            fontSize = 24.sp,
            fontWeight = FontWeight.Bold,
            letterSpacing = 2.sp,
            fontFamily = GoogleSans
        )
        Row(
            verticalAlignment = Alignment.CenterVertically,
            horizontalArrangement = Arrangement.spacedBy(4.dp)
        ) {
            Text(
                text = timeDf.format(Date(now)),
                color = Color(0xFFE8EAED),
                fontSize = 14.sp,
                fontFamily = FontFamily.Monospace,
                fontWeight = FontWeight.Medium
            )
            Text(
                text = zoneDf.format(Date(now)),
                color = Color(0xFF5F6368),
                fontSize = 11.sp,
                fontFamily = FontFamily.Monospace
            )
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Stat cards
// ─────────────────────────────────────────────────────────────────────────────

@Composable
private fun StatRow(
    total: Int,
    critical: Int,
    autoSos: Int,
    totalHistory: List<Int>,
    criticalHistory: List<Int>,
    autoHistory: List<Int>
) {
    Row(
        modifier = Modifier.fillMaxWidth(),
        horizontalArrangement = Arrangement.spacedBy(12.dp)
    ) {
        StatCard(
            label = "TOTAL",
            value = total,
            valueColor = OmniMeshColors.White,
            glowColor = OmniMeshColors.MediumBlue,
            history = totalHistory,
            modifier = Modifier.weight(1f)
        )
        StatCard(
            label = "CRITICAL",
            value = critical,
            valueColor = OmniMeshColors.MediumRed,
            glowColor = OmniMeshColors.MediumRed,
            history = criticalHistory,
            border = OmniMeshColors.MediumRed.copy(alpha = 0.3f),
            modifier = Modifier.weight(1f)
        )
        StatCard(
            label = "AUTO-SOS",
            value = autoSos,
            valueColor = OmniMeshColors.Yellow,
            glowColor = OmniMeshColors.Yellow,
            history = autoHistory,
            modifier = Modifier.weight(1f)
        )
    }
}

@Composable
private fun StatCard(
    label: String,
    value: Int,
    valueColor: Color,
    glowColor: Color,
    history: List<Int>,
    modifier: Modifier = Modifier,
    border: Color? = null
) {
    val animated by animateIntAsState(
        targetValue = value,
        animationSpec = tween(800),
        label = "stat-$label"
    )
    var previousValue by remember { mutableStateOf(value) }
    val glow = remember(label) { Animatable(0f) }
    LaunchedEffect(value) {
        if (value > previousValue) {
            glow.snapTo(1f)
            glow.animateTo(0f, animationSpec = tween(800))
        }
        previousValue = value
    }
    val glowBorder = BorderStroke(
        1.dp,
        (border ?: glowColor.copy(alpha = 0.28f)).copy(alpha = 0.35f + glow.value * 0.65f)
    )
    Surface(
        modifier = modifier,
        shape = RoundedCornerShape(12.dp),
        color = OmniMeshColors.DarkSurface,
        border = glowBorder
    ) {
        Box {
            if (glow.value > 0.01f) {
                Box(
                    modifier = Modifier
                        .fillMaxSize()
                        .background(glowColor.copy(alpha = 0.10f * glow.value), RoundedCornerShape(12.dp))
                )
            }
            Column(
                modifier = Modifier.padding(horizontal = 20.dp, vertical = 18.dp),
                verticalArrangement = Arrangement.spacedBy(6.dp)
            ) {
                Text(
                    text = label,
                    color = Color(0xFF9AA0A6),
                    fontSize = 11.sp,
                    fontFamily = FontFamily.Monospace,
                    letterSpacing = 1.5.sp,
                    fontWeight = FontWeight.Medium
                )
                Text(
                    text = animated.toString(),
                    color = valueColor,
                    fontSize = 48.sp,
                    fontWeight = FontWeight.W300,
                    lineHeight = 52.sp
                )
                Sparkline(
                    values = history,
                    color = glowColor,
                    modifier = Modifier
                        .fillMaxWidth()
                        .height(22.dp)
                )
            }
        }
    }
}

@Composable
private fun Sparkline(values: List<Int>, color: Color, modifier: Modifier = Modifier) {
    Canvas(modifier = modifier) {
        if (values.isEmpty()) return@Canvas
        val safe = if (values.size == 1) listOf(values.first(), values.first()) else values
        val min = safe.minOrNull()?.toFloat() ?: 0f
        val max = safe.maxOrNull()?.toFloat() ?: 1f
        val range = (max - min).coerceAtLeast(1f)
        val stepX = size.width / (safe.size - 1).coerceAtLeast(1)
        val path = Path()
        safe.forEachIndexed { idx, v ->
            val x = idx * stepX
            val y = size.height - ((v - min) / range) * (size.height - 3f) - 1.5f
            if (idx == 0) path.moveTo(x, y) else path.lineTo(x, y)
            drawCircle(color.copy(alpha = 0.8f), radius = 1.5f, center = Offset(x, y))
        }
        drawPath(path = path, color = color.copy(alpha = 0.8f), style = androidx.compose.ui.graphics.drawscope.Stroke(width = 1.8f))
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Structural collapse protocol banner
// ─────────────────────────────────────────────────────────────────────────────

@OptIn(ExperimentalFoundationApi::class)
@Composable
private fun CollapseProtocolBanner(autoCount: Int) {
    val stripePx = with(LocalDensity.current) { 18.dp.toPx() }
    val pulse = rememberInfiniteTransition(label = "collapsePulse")
    val borderAlpha by pulse.animateFloat(
        initialValue = 0.72f,
        targetValue = 1f,
        animationSpec = infiniteRepeatable(animation = tween(950), repeatMode = RepeatMode.Reverse),
        label = "collapseBorderPulse"
    )
    val diamondPulse by pulse.animateFloat(
        initialValue = 0.88f,
        targetValue = 1f,
        animationSpec = infiniteRepeatable(animation = tween(700), repeatMode = RepeatMode.Reverse),
        label = "collapseDiamondPulse"
    )
    Box(
        modifier = Modifier
            .fillMaxWidth()
            .height(46.dp)
            .clip(RoundedCornerShape(8.dp))
            .border(
                width = 2.dp,
                brush = Brush.horizontalGradient(
                    colors = listOf(
                        OmniMeshColors.MediumRed.copy(alpha = 0.65f + 0.35f * borderAlpha),
                        Color(0xFFFF6659),
                        OmniMeshColors.MediumRed.copy(alpha = 0.65f + 0.35f * borderAlpha),
                    )
                ),
                shape = RoundedCornerShape(8.dp)
            )
    ) {
        Canvas(modifier = Modifier.fillMaxSize()) {
            var x = 0f
            var i = 0
            while (x < size.width + stripePx) {
                drawRect(
                    color = if (i % 2 == 0) Color(0xFF7B1510) else Color(0xFF5C0E0A),
                    topLeft = Offset(x, 0f),
                    size = Size(stripePx, size.height)
                )
                x += stripePx
                i++
            }
        }
        Box(
            modifier = Modifier
                .align(Alignment.CenterStart)
                .width(5.dp)
                .fillMaxHeight()
                .background(
                    Brush.verticalGradient(
                        colors = listOf(
                            Color(0xFFFF8A80),
                            OmniMeshColors.MediumRed,
                            Color(0xFFB31412)
                        )
                    )
                )
        )
        Row(
            modifier = Modifier
                .fillMaxSize()
                .padding(start = 5.dp, end = 10.dp),
            verticalAlignment = Alignment.CenterVertically
        ) {
            Spacer(Modifier.width(8.dp))
            Box(
                modifier = Modifier
                    .size(11.dp)
                    .graphicsLayer {
                        rotationZ = 45f
                        alpha = diamondPulse
                    }
                    .background(OmniMeshColors.MediumRed, RoundedCornerShape(1.dp))
            )
            Spacer(Modifier.width(10.dp))
            Text(
                text = "⚠ STRUCTURAL COLLAPSE PROTOCOL — $autoCount AUTO-SOS SIGNALS DETECTED — AWAIT ENGINEERING CLEARANCE BEFORE GROUND ENTRY",
                color = Color.White,
                fontSize = 11.sp,
                fontWeight = FontWeight.Bold,
                letterSpacing = 1.3.sp,
                fontFamily = FontFamily.Monospace,
                maxLines = 1,
                modifier = Modifier
                    .weight(1f)
                    .basicMarquee(initialDelayMillis = 600)
            )
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Gemini terminal — typewriter analysis output
// ─────────────────────────────────────────────────────────────────────────────

@Composable
private fun GeminiTerminalPanel(
    analysisText: String,
    hasResult: Boolean,
    estimatedCasualties: Int?,
    analyzing: Boolean,
    packetCount: Int,
    onRun: () -> Unit,
    onSpeak: (String) -> Unit
) {
    var typedLineCount by remember { mutableStateOf(1) }
    var loadingLineCount by remember { mutableStateOf(0) }
    val scan = rememberInfiniteTransition(label = "terminalScanline")
    val scanProgress by scan.animateFloat(
        initialValue = 0f,
        targetValue = 1f,
        animationSpec = infiniteRepeatable(
            animation = tween(3500),
            repeatMode = RepeatMode.Restart
        ),
        label = "terminalScanlineProgress"
    )

    Surface(
        modifier = Modifier.fillMaxWidth(),
        shape = RoundedCornerShape(10.dp),
        color = OmniMeshColors.DarkBackground,
        border = BorderStroke(1.dp, OmniMeshColors.MediumGreen.copy(alpha = 0.4f))
    ) {
        Column {
            TerminalTitleBar()
            Box {
                Column(
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(16.dp),
                    verticalArrangement = Arrangement.spacedBy(10.dp)
                ) {
                    Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.End) {
                        Text(
                            text = "LINES ${(typedLineCount + loadingLineCount).coerceAtLeast(1)}",
                            color = OmniMeshColors.MediumGreen.copy(alpha = 0.55f),
                            fontSize = 10.sp,
                            fontFamily = FontFamily.Monospace
                        )
                    }

                    AnimatedVisibility(visible = analyzing) {
                        LoadingSequence(onVisibleLinesChanged = { loadingLineCount = it })
                    }

                    if (hasResult) {
                        TypewriterText(
                            text = analysisText,
                            analyzing = false,
                            onLineCountChanged = { typedLineCount = it }
                        )
                        Text(
                            text = "Model casualty projection: ${estimatedCasualties ?: 0}",
                            color = OmniMeshColors.Yellow,
                            fontSize = 13.sp,
                            fontFamily = FontFamily.Monospace,
                            style = terminalGlowStyle()
                        )
                    } else if (!analyzing) {
                        typedLineCount = 1
                        loadingLineCount = 0
                        Text(
                            text = "> Tap RUN to analyze $packetCount active packets.",
                            color = OmniMeshColors.MediumGreen.copy(alpha = 0.7f),
                            fontSize = 13.sp,
                            fontFamily = FontFamily.Monospace,
                            style = terminalGlowStyle()
                        )
                    }

                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.spacedBy(8.dp)
                    ) {
                        Button(
                            onClick = onRun,
                            modifier = Modifier.weight(1f),
                            colors = ButtonDefaults.buttonColors(
                                containerColor = OmniMeshColors.MediumGreen
                            ),
                            shape = RoundedCornerShape(6.dp)
                        ) {
                            Text(
                                text = if (!hasResult) "▶ RUN ANALYSIS"
                                else "↻ RE-ANALYZE",
                                fontWeight = FontWeight.Bold,
                                fontSize = 12.sp,
                                letterSpacing = 1.4.sp,
                                fontFamily = GoogleSans
                            )
                        }
                        if (hasResult) {
                            OutlinedButton(
                                onClick = { onSpeak(analysisText) },
                                border = BorderStroke(1.dp, OmniMeshColors.MediumGreen.copy(alpha = 0.6f)),
                                colors = ButtonDefaults.outlinedButtonColors(
                                    contentColor = OmniMeshColors.MediumGreen
                                ),
                                shape = RoundedCornerShape(6.dp)
                            ) {
                                Text(
                                    text = "🔊",
                                    fontSize = 14.sp
                                )
                            }
                        }
                    }
                }
                Canvas(modifier = Modifier.fillMaxSize()) {
                    val y = scanProgress * size.height
                    drawRect(
                        color = OmniMeshColors.MediumGreen.copy(alpha = 0.035f),
                        topLeft = Offset(0f, y),
                        size = Size(size.width, 2.dp.toPx())
                    )
                }
            }
        }
    }
}

@Composable
private fun TerminalTitleBar() {
    Surface(
        color = OmniMeshColors.DarkElevated,
        modifier = Modifier
            .fillMaxWidth()
            .height(36.dp)
    ) {
        Row(
            modifier = Modifier.padding(horizontal = 12.dp),
            verticalAlignment = Alignment.CenterVertically,
            horizontalArrangement = Arrangement.spacedBy(8.dp)
        ) {
            TerminalDot(OmniMeshColors.MediumRed)
            TerminalDot(OmniMeshColors.Yellow)
            TerminalDot(OmniMeshColors.MediumGreen)
            Spacer(Modifier.width(8.dp))
            Text(
                text = "GEMINI 1.5 FLASH · DISPATCH AGENT",
                color = OmniMeshColors.MediumGreen,
                    fontSize = 11.sp,
                fontFamily = FontFamily.Monospace,
                fontWeight = FontWeight.Medium
            )
        }
    }
}

@Composable
private fun TerminalDot(color: Color) {
    Box(
        modifier = Modifier
            .size(10.dp)
            .background(color, CircleShape)
    )
}

@Composable
private fun TypewriterText(text: String, analyzing: Boolean, onLineCountChanged: (Int) -> Unit) {
    var displayed by remember(text) { mutableStateOf("") }
    var cursorVisible by remember { mutableStateOf(true) }
    var cursorFlash by remember { mutableStateOf(false) }

    LaunchedEffect(text) {
        displayed = ""
        onLineCountChanged(1)
        text.forEachIndexed { i, _ ->
            delay(15)
            displayed = text.substring(0, i + 1)
            onLineCountChanged(displayed.lines().size.coerceAtLeast(1))
            cursorFlash = true
            delay(30)
            cursorFlash = false
        }
    }

    LaunchedEffect(Unit) {
        while (true) {
            delay(500)
            cursorVisible = !cursorVisible
        }
    }

    val showGlyph = analyzing || displayed.length < text.length
    Text(
        text = displayed + if (showGlyph && cursorVisible) "█" else "",
        color = OmniMeshColors.MediumGreen,
        fontSize = 13.sp,
        fontFamily = FontFamily.Monospace,
        style = terminalGlowStyle(flash = cursorFlash)
    )
}

@Composable
private fun LoadingSequence(onVisibleLinesChanged: (Int) -> Unit) {
    val lines = listOf(
        "> INITIALIZING...",
        "> LOADING PACKETS...",
        "> RUNNING CLUSTER ANALYSIS..."
    )
    var visibleCount by remember { mutableStateOf(0) }
    LaunchedEffect(Unit) {
        for (i in 1..lines.size) {
            visibleCount = i
            onVisibleLinesChanged(i)
            delay(800)
        }
    }
    Column(verticalArrangement = Arrangement.spacedBy(2.dp)) {
        lines.forEachIndexed { index, line ->
            AnimatedVisibility(
                visible = visibleCount > index,
                enter = fadeIn(animationSpec = tween(260)),
                exit = fadeOut(animationSpec = tween(120))
            ) {
                Text(
                    text = line,
                    color = OmniMeshColors.MediumGreen,
                    fontSize = 12.sp,
                    fontFamily = FontFamily.Monospace,
                    style = terminalGlowStyle()
                )
            }
        }
    }
}

@Composable
private fun terminalGlowStyle(flash: Boolean = false): TextStyle = TextStyle(
    shadow = Shadow(
        color = OmniMeshColors.MediumGreen.copy(alpha = if (flash) 0.45f else 0.30f),
        offset = Offset.Zero,
        blurRadius = if (flash) 10f else 6f
    )
)

// ─────────────────────────────────────────────────────────────────────────────
// Zone assignment cards
// ─────────────────────────────────────────────────────────────────────────────

@Composable
private fun ZoneAssignments(zoneAssignments: Map<String, String>) {
    Surface(
        modifier = Modifier.fillMaxWidth(),
        shape = RoundedCornerShape(10.dp),
        color = OmniMeshColors.DarkSurface
    ) {
        Column(
            modifier = Modifier.padding(16.dp),
            verticalArrangement = Arrangement.spacedBy(12.dp)
        ) {
            Text(
                text = "ZONE ASSIGNMENTS",
                color = OmniMeshColors.Grey,
                fontSize = 10.sp,
                fontWeight = FontWeight.Bold,
                letterSpacing = 1.8.sp,
                fontFamily = GoogleSans
            )
            zoneAssignments.entries.forEachIndexed { index, (zone, instruction) ->
                AnimatedVisibility(
                    visible = true,
                    enter = fadeIn(animationSpec = tween(220, delayMillis = index * 50)) +
                            slideInVertically(animationSpec = tween(260, delayMillis = index * 50)) { it / 4 }
                ) {
                    ZoneCard(zone = zone, instruction = instruction)
                }
            }
        }
    }
}

@Composable
private fun ZoneCard(zone: String, instruction: String) {
    Box(
        modifier = Modifier
            .fillMaxWidth()
            .border(
                width = 0.dp,
                color = Color.Transparent,
                shape = RoundedCornerShape(2.dp)
            )
    ) {
        Row(modifier = Modifier.fillMaxWidth()) {
            Box(
                modifier = Modifier
                    .width(3.dp)
                    .height(48.dp)
                    .background(OmniMeshColors.MediumBlue)
            )
            Column(
                modifier = Modifier
                    .padding(start = 10.dp)
                    .fillMaxWidth(),
                verticalArrangement = Arrangement.spacedBy(2.dp)
            ) {
                Text(
                    text = "ZONE ${zone.uppercase()}",
                    color = OmniMeshColors.MediumBlue,
                    fontSize = 10.sp,
                    fontWeight = FontWeight.Bold,
                    letterSpacing = 1.4.sp,
                    fontFamily = FontFamily.Monospace
                )
                Text(
                    text = instruction,
                    color = OmniMeshColors.White,
                    fontSize = 13.sp,
                    fontFamily = GoogleSans
                )
            }
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Critical alert box
// ─────────────────────────────────────────────────────────────────────────────

@Composable
private fun CriticalAlertBox(message: String) {
    Surface(
        modifier = Modifier.fillMaxWidth(),
        shape = RoundedCornerShape(8.dp),
        color = OmniMeshColors.MediumRed.copy(alpha = 0.1f),
        border = BorderStroke(1.dp, OmniMeshColors.MediumRed)
    ) {
        Text(
            text = "⚑ CRITICAL: $message",
            color = OmniMeshColors.MediumRed,
            fontSize = 12.sp,
            fontFamily = FontFamily.Monospace,
            modifier = Modifier.padding(12.dp)
        )
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Packet table
// ─────────────────────────────────────────────────────────────────────────────

@Composable
private fun PacketTable(packets: List<TriagePacket>) {
    val sorted = packets.sortedBy { it.urgencyPriority() }

    Surface(
        modifier = Modifier.fillMaxWidth(),
        shape = RoundedCornerShape(10.dp),
        color = OmniMeshColors.DarkSurface
    ) {
        Column(
            modifier = Modifier.fillMaxWidth()
        ) {
            // Header
            Row(
                modifier = Modifier
                    .fillMaxWidth()
                    .background(Color(0xFF161B22))
                    .padding(horizontal = 12.dp, vertical = 8.dp),
                verticalAlignment = Alignment.CenterVertically
            ) {
                TableHeaderCell("#", modifier = Modifier.width(32.dp))
                TableHeaderCell("URGENCY", modifier = Modifier.width(80.dp))
                TableHeaderCell("INJURY", modifier = Modifier.weight(1f))
                TableHeaderCell("CONF·TYPE", modifier = Modifier.width(80.dp))
            }

            sorted.forEachIndexed { index, p ->
                PacketRow(packet = p, index = index)
            }

            if (sorted.isEmpty()) {
                Text(
                    text = "(no active packets)",
                    color = OmniMeshColors.Grey,
                    fontSize = 12.sp,
                    fontFamily = FontFamily.Monospace,
                    modifier = Modifier.padding(16.dp)
                )
            }
        }
    }
}

@Composable
private fun TableHeaderCell(label: String, modifier: Modifier) {
    Text(
        text = label,
        color = Color(0xFF9AA0A6),
        fontSize = 12.sp,
        fontWeight = FontWeight.Bold,
        fontFamily = FontFamily.Monospace,
        modifier = modifier
    )
}

@Composable
private fun PacketRow(
    packet: TriagePacket,
    index: Int,
) {
    val isRed = packet.urgency == "RED"
        Row(
        modifier = Modifier
            .fillMaxWidth()
            .height(40.dp)
            .background(
                when {
                    isRed -> Color(0xFFEA4335).copy(alpha = 0.06f)
                    index % 2 == 0 -> Color(0xFF0D1117)
                    else -> Color(0xFF0A0A0A)
                }
            )
            .then(
                if (isRed) Modifier.border(
                    BorderStroke(2.dp, OmniMeshColors.MediumRed),
                    RoundedCornerShape(0.dp)
                ) else Modifier
            )
            .padding(horizontal = 12.dp, vertical = 6.dp),
        verticalAlignment = Alignment.CenterVertically
    ) {
        // Spec: RED rows have a 2dp left red border. We render it as a
        // dedicated rail so it stays visible on dark alternating rows.
        Box(
            modifier = Modifier
                .width(if (isRed) 2.dp else 0.dp)
                .height(32.dp)
                .background(if (isRed) OmniMeshColors.MediumRed else Color.Transparent)
        )
        Spacer(Modifier.width(if (isRed) 8.dp else 0.dp))
        Text(
            text = (index + 1).toString(),
            color = Color(0xFF5F6368),
            fontSize = 13.sp,
            fontFamily = FontFamily.Monospace,
            modifier = Modifier.width(32.dp)
        )
        Box(modifier = Modifier.width(80.dp)) {
            UrgencyPill(packet.urgency, color = urgencyColor(packet.urgency))
        }
        Text(
            text = packet.injury.take(40).replace('_', ' '),
            color = Color(0xFFE8EAED),
            fontSize = 13.sp,
            fontFamily = GoogleSans,
            maxLines = 1,
            modifier = Modifier.weight(1f)
        )
        Text(
            text = "${(packet.confidence * 100).toInt()}%·${if (packet.isAutoGenerated) "AUTO" else "MANUAL"}",
            color = Color(0xFF9AA0A6),
            fontSize = 11.sp,
            fontFamily = FontFamily.Monospace,
            fontWeight = FontWeight.Medium,
            modifier = Modifier.width(80.dp),
            maxLines = 1
        )
    }
}

@Composable
private fun UrgencyPill(label: String, color: Color, modifier: Modifier = Modifier) {
    Box(modifier = modifier) {
        Surface(
            shape = RoundedCornerShape(4.dp),
            color = color.copy(alpha = 0.15f),
            border = BorderStroke(1.dp, color.copy(alpha = 0.4f))
        ) {
            Text(
                text = label,
                color = color,
                fontSize = 10.sp,
                fontFamily = FontFamily.Monospace,
                fontWeight = FontWeight.Bold,
                letterSpacing = 0.6.sp,
                modifier = Modifier.padding(horizontal = 8.dp, vertical = 3.dp)
            )
        }
    }
}
