const { onDocumentWritten } = require("firebase-functions/v2/firestore");
const { onDocumentCreated } = require("firebase-functions/v2/firestore");
const { setGlobalOptions } = require("firebase-functions/v2");
const admin = require("firebase-admin");
const { GoogleGenerativeAI } = require("@google/generative-ai");

admin.initializeApp();
const db = admin.firestore();

// Set region to us-central1 (default, closest to most Firebase projects)
setGlobalOptions({ region: "us-central1" });

exports.onRedPacketTriggerDispatch = onDocumentWritten(
  "packets/{packetId}",
  async (event) => {
    const data = event.data?.after?.data();
    if (!data || data.urgency !== "RED") return null;

    // Debounce — only re-run if last analysis was more than 30 seconds ago
    const analysisRef = db.collection("dispatch_analysis").doc("latest");
    const existing = await analysisRef.get();
    if (existing.exists) {
      const lastTs = existing.data().generatedAt?.toMillis() || 0;
      if (Date.now() - lastTs < 30000) return null;
    }

    // Fetch all current packets from Firestore
    const snapshot = await db.collection("packets").get();
    const packets = snapshot.docs.map((d) => d.data());

    const red = packets.filter((p) => p.urgency === "RED");
    const yellow = packets.filter((p) => p.urgency === "YELLOW");
    const green = packets.filter((p) => p.urgency === "GREEN");
    const autoGenerated = packets.filter((p) => p.isAutoGenerated === true);

    const prompt = buildPrompt(packets, red, yellow, green, autoGenerated);
    const analysis = await callGemini(prompt);

    await analysisRef.set({
      ...analysis,
      generatedAt: admin.firestore.FieldValue.serverTimestamp(),
      packetCount: packets.length,
    });

    return null;
  }
);

function buildPrompt(packets, red, yellow, green, auto) {
  const packetSummary = packets
    .map(
      (p) =>
        `ID:${p.id} urgency:${p.urgency} injury:"${p.injury}" ` +
        `lat:${p.lat} lon:${p.lon} confidence:${p.confidence} ` +
        `auto:${p.isAutoGenerated} signals:${p.signalSources}`
    )
    .join("\n");

  return `You are an AI incident commander for a mass casualty disaster response.
Analyze this triage zone and return ONLY valid JSON, no markdown, no explanation.

ZONE SUMMARY:
RED (life-threatening): ${red.length}
YELLOW (serious): ${yellow.length}
GREEN (minor): ${green.length}
AUTO-DETECTED (unconscious victims, no user action): ${auto.length}

ACTIVE PACKETS:
${packetSummary}

Return exactly this JSON schema:
{
  "priority_order": ["id1", "id2"],
  "zone_assignments": [
    {
      "zone": "Alpha",
      "packetIds": ["id1"],
      "resources": "2 paramedics + structural team",
      "reasoning": "brief reason"
    }
  ],
  "critical_alert": "string or null",
  "estimated_casualties": 0,
  "analysis": "2-3 sentence tactical summary for incident commander"
}`;
}

const GEMINI_MODEL = process.env.GEMINI_MODEL || "gemini-2.0-flash";

async function callGemini(prompt) {
  const apiKey = process.env.GEMINI_API_KEY;
  const emptyFallback = {
    priority_order: [],
    zone_assignments: [],
    critical_alert: null,
    estimated_casualties: 0,
    analysis:
      "Analysis unavailable. Review packets by priority order.",
  };

  if (!apiKey) {
    console.error("Gemini dispatch error: GEMINI_API_KEY is not set");
    return emptyFallback;
  }

  try {
    const genAI = new GoogleGenerativeAI(apiKey);
    const model = genAI.getGenerativeModel({
      model: GEMINI_MODEL,
      generationConfig: {
        temperature: 0,
        maxOutputTokens: 600,
      },
    });
    const result = await model.generateContent(prompt);
    const text = (result.response.text() || "")
      .replace(/```json\n?/g, "")
      .replace(/```\n?/g, "")
      .trim();
    if (!text) {
      throw new Error("Empty Gemini response");
    }
    try {
      return JSON.parse(text);
    } catch (parseErr) {
      console.error("Gemini JSON parse error:", parseErr);
      return emptyFallback;
    }
  } catch (error) {
    console.error("Gemini dispatch error:", error);
    if (error?.response?.data !== undefined) {
      console.error("Gemini response:", error.response.data);
    }
    return emptyFallback;
  }
}

exports.sendBuddyAlerts = onDocumentCreated(
  "pending_fcm_alerts/{alertId}",
  async (event) => {
    const data = event.data?.data();
    if (!data) return null;

    const { token, title, body, lat, lon } = data;

    try {
      await admin.messaging().send({
        token,
        notification: { title, body },
        data: {
          lat: String(lat),
          lon: String(lon),
          type: "BUDDY_ALERT",
        },
        android: {
          priority: "high",
          notification: {
            sound: "default",
            priority: "max",
            channelId: "omnimesh_alerts",
          },
        },
      });
      await event.data.ref.update({ sentAt: Date.now(), status: "sent" });
    } catch (e) {
      console.error("FCM send failed:", e);
      await event.data.ref.update({ status: "failed", error: e.message });
    }
    return null;
  }
);