package omnimesh.command1.data

import android.util.Log
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.firestore.FirebaseFirestore
import com.google.firebase.firestore.SetOptions
import kotlinx.coroutines.tasks.await

private const val TAG = "FirebaseSyncManager"
private const val DEBUG_TAG = "FirebaseSync"
private const val AUTH_TAG = "FirebaseAuth"
private const val FIRESTORE_TAG = "FirebaseFirestore"
private const val COLLECTION = "packets"

class FirebaseSyncManager(
    private val repository: PacketRepository
) {
    private val db = FirebaseFirestore.getInstance()
    private val auth = FirebaseAuth.getInstance()

    // ─────────────────────────────────────────────
    // AUTHENTICATION
    // 💡 We use anonymous auth — no signup needed for victims.
    // Each device gets a unique anonymous UID automatically.
    // This satisfies Firestore security rules (request.auth != null).
    // ─────────────────────────────────────────────

    suspend fun ensureAuthenticated() {
        if (auth.currentUser == null) {
            try {
                Log.d(AUTH_TAG, "No current user — signing in anonymously")
                auth.signInAnonymously().await()
                Log.d(AUTH_TAG, "Anonymous sign-in success uid=${auth.currentUser?.uid}")
            } catch (e: Exception) {
                Log.e(AUTH_TAG, "Anonymous sign-in failed", e)
                throw e
            }
        } else {
            Log.d(AUTH_TAG, "Already authenticated uid=${auth.currentUser?.uid}")
        }
    }

    // ─────────────────────────────────────────────
    // SYNC — upload all unsynced local packets to Firestore
    // ─────────────────────────────────────────────

    suspend fun syncPendingPackets(): SyncResult {
        return try {
            ensureAuthenticated()
            val unsynced = repository.getUnsyncedPackets()

            if (unsynced.isEmpty()) {
                Log.d(DEBUG_TAG, "Nothing to sync")
                return SyncResult(uploaded = 0, failed = 0)
            }

            Log.d(DEBUG_TAG, "Syncing ${unsynced.size} packet(s) to Firestore")
            Log.d(FIRESTORE_TAG, "Preparing batch write to collection=$COLLECTION")

            var uploaded = 0
            var failed = 0

            // 💡 Batch writes — instead of 50 separate network calls,
            // Firestore batches up to 500 writes in a single request.
            // Much faster and uses less data — critical on a weak signal.
            val batch = db.batch()

            for (packet in unsynced) {
                val doc = db.collection(COLLECTION).document(packet.id)
                Log.d(FIRESTORE_TAG, "Queueing packet document id=${packet.id}")
                batch.set(doc, packet.toFirestoreMap(), SetOptions.merge())
            }

            batch.commit()
                .addOnSuccessListener {
                    Log.d(
                        DEBUG_TAG,
                        "PACKET SUCCESS count=${unsynced.size} ids=${unsynced.joinToString { it.id }}"
                    )
                }
                .addOnFailureListener { e ->
                    Log.e(
                        DEBUG_TAG,
                        "PACKET FAILED count=${unsynced.size} ids=${unsynced.joinToString { it.id }}",
                        e
                    )
                }
                .await()
            uploaded = unsynced.size

            // Mark all as synced in local DB
            unsynced.forEach { repository.markSynced(it.id) }

            Log.d(FIRESTORE_TAG, "Batch write complete collection=$COLLECTION uploaded=$uploaded")
            Log.d(DEBUG_TAG, "Sync complete — uploaded $uploaded packet(s)")
            SyncResult(uploaded = uploaded, failed = failed)

        } catch (e: Exception) {
            Log.e(DEBUG_TAG, "Sync failed", e)
            Log.e(FIRESTORE_TAG, "Firestore write failed for collection=$COLLECTION", e)
            SyncResult(uploaded = 0, failed = -1, error = e.message)
        }
    }

    // Firestore document structure
    // 💡 We store lat/lon as a GeoPoint so Firestore's
    // geo-query features work natively with Google Maps
    private fun TriagePacket.toFirestoreMap(): Map<String, Any> = mapOf(
        "id" to id,
        "urgency" to urgency,
        "injury" to injury,
        "loc" to loc,
        "lat" to lat,
        "lon" to lon,
        "ts" to ts,
        "confidence" to confidence,
        "signalSources" to signalSources,
        "isAutoGenerated" to isAutoGenerated,
        "hopCount" to hopCount,
        "originDeviceId" to originDeviceId,
        "syncedAt" to System.currentTimeMillis()
    )
}

data class SyncResult(
    val uploaded: Int,
    val failed: Int,
    val error: String? = null
)
