package omnimesh.command1.data

import androidx.room.Entity
import androidx.room.PrimaryKey
import org.json.JSONObject

// 💡 @Entity tells Room "make a database table for this class"
// Every field becomes a column in the table
@Entity(tableName = "packets")
data class TriagePacket(
    @PrimaryKey val id: String,           // Unique 8-char ID per packet
    val urgency: String,                   // RED | YELLOW | GREEN | BLACK
    val injury: String,                    // "compound_fracture_femur" etc
    val loc: String,                       // Human location description
    val lat: Double,                       // GPS latitude
    val lon: Double,                       // GPS longitude
    val ts: Long,                          // Unix timestamp (ms)
    val confidence: Float,                 // 0.0–1.0 from meta-classifier
    val signalSources: String,            // "VAG" = Vision+Audio+Gemini
    val isAutoGenerated: Boolean,          // true = collapse detected passively
    val synced: Boolean = false,           // false = not yet sent to Firebase
    val hopCount: Int = 0,                 // how many mesh hops this packet traveled
    val originDeviceId: String = ""        // which phone originally created it
) {
    // 💡 These functions convert the packet to/from raw bytes
    // This is what actually gets transmitted over Bluetooth in the mesh
    fun toBytes(): ByteArray = toJson().toByteArray(Charsets.UTF_8)

    fun toJson(): String = JSONObject().apply {
        put("id", id)
        put("urgency", urgency)
        put("injury", injury)
        put("loc", loc)
        put("lat", lat)
        put("lon", lon)
        put("ts", ts)
        put("confidence", confidence)
        put("sources", signalSources)
        put("auto", isAutoGenerated)
        put("hops", hopCount)
        put("origin", originDeviceId)
    }.toString()

    // Maps urgency string to a priority number for sorting
    // 💡 Lower number = higher priority. RED patients get transmitted first.
    fun urgencyPriority(): Int = when (urgency) {
        "RED" -> 1
        "YELLOW" -> 2
        "GREEN" -> 3
        "BLACK" -> 4
        else -> 5
    }

    companion object {
        fun fromBytes(bytes: ByteArray): TriagePacket {
            val json = JSONObject(String(bytes, Charsets.UTF_8))
            return TriagePacket(
                id = json.getString("id"),
                urgency = json.getString("urgency"),
                injury = json.getString("injury"),
                loc = json.getString("loc"),
                lat = json.getDouble("lat"),
                lon = json.getDouble("lon"),
                ts = json.getLong("ts"),
                confidence = json.optDouble("confidence", 0.5).toFloat(),
                signalSources = json.optString("sources", ""),
                isAutoGenerated = json.optBoolean("auto", false),
                hopCount = json.optInt("hops", 0),
                originDeviceId = json.optString("origin", "")
            )
        }

        // 💡 Factory method — creates a "test" packet for development
        // You'll use this to populate the map UI before real ML is connected
        fun mockRed(lat: Double, lon: Double): TriagePacket = TriagePacket(
            id = "mock_${System.currentTimeMillis()}",
            urgency = "RED",
            injury = "compound_fracture_femur",
            loc = "basement_B2",
            lat = lat,
            lon = lon,
            ts = System.currentTimeMillis(),
            confidence = 0.94f,
            signalSources = "VAG",
            isAutoGenerated = false
        )
    }
}
