package omnimesh.command1.command

import omnimesh.command1.data.TriagePacket

object DataQualityCalculator {

    fun compute(packet: TriagePacket): DataQuality {
        if (packet.signalSources.contains("FALSE")) {
            return DataQuality(
                level = QualityLevel.DISPUTED,
                label = "False positive",
                detail = "Marked as false positive by responder",
                barsFilled = 0,
                isFalsePositive = true
            )
        }
        if (packet.signalSources.contains("CONFIRMED")) {
            return DataQuality(
                level = QualityLevel.CONFIRMED,
                label = "Responder confirmed",
                detail = "Physically confirmed by field responder",
                barsFilled = 3,
                isConfirmedByResponder = true
            )
        }

        val sources = packet.signalSources
        val signalCount = listOf(
            sources.contains("M"),
            sources.contains("V"),
            sources.contains("A"),
            sources.contains("C"),
            sources.contains("START"),
        ).count { it }

        val confidence = packet.confidence
        return when {
            signalCount >= 3 && confidence >= 0.80f -> DataQuality(
                level = QualityLevel.HIGH,
                label = "High confidence",
                detail = "$signalCount signals · ${(confidence * 100).toInt()}%",
                barsFilled = 3
            )
            signalCount >= 2 && confidence >= 0.60f -> DataQuality(
                level = QualityLevel.MEDIUM,
                label = "Moderate confidence",
                detail = "$signalCount signals · ${(confidence * 100).toInt()}%",
                barsFilled = 2
            )
            signalCount == 1 && sources == "M" && !packet.isAutoGenerated -> DataQuality(
                level = QualityLevel.LOW,
                label = "Motion only",
                detail = "Single sensor — verify before dispatching",
                barsFilled = 1
            )
            packet.isAutoGenerated && confidence >= 0.85f -> DataQuality(
                level = QualityLevel.MEDIUM,
                label = "Auto-detected",
                detail = "Passive collapse detection · ${(confidence * 100).toInt()}%",
                barsFilled = 2
            )
            else -> DataQuality(
                level = QualityLevel.LOW,
                label = "Low confidence",
                detail = "Unverified · ${(confidence * 100).toInt()}%",
                barsFilled = 1
            )
        }
    }
}
