package omnimesh.command1.ml

import android.util.Log
import com.google.ai.client.generativeai.GenerativeModel
import com.google.ai.client.generativeai.type.generationConfig
import omnimesh.command1.data.TriagePacket

class DispatchAgent(private val apiKey: String) {

    data class DispatchRecommendation(
        val rawAnalysis: String,
        val zoneAssignments: Map<String, String>,
        val estimatedCasualties: Int,
        val criticalAlert: String?
    )

    private val model by lazy {
        GenerativeModel(
            modelName = "gemini-2.5-flash",
            apiKey = apiKey,
            generationConfig = generationConfig {
                temperature = 0.3f
                maxOutputTokens = 1024
            }
        )
    }

    suspend fun analyzeZone(packets: List<TriagePacket>): DispatchRecommendation {
        if (packets.isEmpty()) {
            return DispatchRecommendation(
                rawAnalysis = "No active triage packets. Hold teams at staging and continue scan.",
                zoneAssignments = emptyMap(),
                estimatedCasualties = 0,
                criticalAlert = null
            )
        }

        if (apiKey.isBlank()) {
            Log.w(TAG, "No Gemini API key — using local fallback")
            return localFallback(packets)
        }

        return try {
            callGemini(packets)
        } catch (e: Exception) {
            Log.e(TAG, "Gemini API call failed, using local fallback", e)
            localFallback(packets)
        }
    }

    private suspend fun callGemini(packets: List<TriagePacket>): DispatchRecommendation {
        val packetSummary = packets.mapIndexed { i, p ->
            "#${i + 1} | ${p.urgency} | ${p.injury} | lat=${p.lat}, lon=${p.lon} | " +
                "confidence=${p.confidence} | ${if (p.isAutoGenerated) "AUTO" else "MANUAL"} | " +
                "signals=${p.signalSources}"
        }.joinToString("\n")

        val red = packets.count { it.urgency == "RED" }
        val yellow = packets.count { it.urgency == "YELLOW" }
        val green = packets.count { it.urgency == "GREEN" }
        val auto = packets.count { it.isAutoGenerated }

        val prompt = """
You are OmniMesh Dispatch AI — an incident command assistant for mass casualty disaster response.

SITUATION REPORT:
- Total active triage packets: ${packets.size}
- RED (critical): $red | YELLOW (delayed): $yellow | GREEN (minor): $green
- Auto-detected (sensor-based): $auto | Manual reports: ${packets.size - auto}

PACKET DATA:
$packetSummary

TASK: Analyze this data as an experienced incident commander would. Provide:

1. SITUATION ANALYSIS (2-3 sentences): What is happening? Assess severity, clustering, and trends.

2. ZONE ASSIGNMENTS: Divide response into 3 zones (Alpha, Bravo, Charlie). For each zone give a specific, actionable order (1 sentence each). Base assignments on the actual injury types and locations in the data.

3. CASUALTY PROJECTION: Your best estimate of total casualties including unreported (integer).

4. CRITICAL ALERT: If you detect a pattern suggesting structural collapse, chemical exposure, crush injuries, or mass trauma, state it in one urgent sentence. If no critical pattern, write "NONE".

FORMAT your response EXACTLY like this (no markdown, no extra text):
ANALYSIS: <your situation analysis>
ZONE_ALPHA: <order for alpha>
ZONE_BRAVO: <order for bravo>
ZONE_CHARLIE: <order for charlie>
CASUALTIES: <integer>
ALERT: <critical alert or NONE>
""".trimIndent()

        Log.d(TAG, "Sending ${packets.size} packets to Gemini for analysis")
        val response = model.generateContent(prompt)
        val text = response.text ?: throw Exception("Empty Gemini response")
        Log.d(TAG, "Gemini response: $text")

        return parseGeminiResponse(text, packets)
    }

    private fun parseGeminiResponse(
        text: String,
        packets: List<TriagePacket>
    ): DispatchRecommendation {
        val lines = text.lines().associate { line ->
            val colonIndex = line.indexOf(':')
            if (colonIndex > 0) {
                line.substring(0, colonIndex).trim().uppercase() to
                    line.substring(colonIndex + 1).trim()
            } else {
                "" to line
            }
        }

        val analysis = lines["ANALYSIS"] ?: text.take(200)
        val zoneAlpha = lines["ZONE_ALPHA"] ?: "Rapid triage sweep."
        val zoneBravo = lines["ZONE_BRAVO"] ?: "Stabilize and evacuate."
        val zoneCharlie = lines["ZONE_CHARLIE"] ?: "Perimeter search."
        val casualties = lines["CASUALTIES"]?.filter { it.isDigit() }?.toIntOrNull()
            ?: packets.size
        val alert = lines["ALERT"]?.takeIf {
            it.uppercase() != "NONE" && it.isNotBlank()
        }

        return DispatchRecommendation(
            rawAnalysis = analysis,
            zoneAssignments = linkedMapOf(
                "alpha" to zoneAlpha,
                "bravo" to zoneBravo,
                "charlie" to zoneCharlie
            ),
            estimatedCasualties = casualties,
            criticalAlert = alert
        )
    }

    private fun localFallback(packets: List<TriagePacket>): DispatchRecommendation {
        val red = packets.count { it.urgency == "RED" }
        val yellow = packets.count { it.urgency == "YELLOW" }
        val auto = packets.count { it.isAutoGenerated }

        return DispatchRecommendation(
            rawAnalysis = buildString {
                append("Active packets: ${packets.size}. ")
                append("RED: $red, YELLOW: $yellow, AUTO-SOS: $auto. ")
                append("[Local fallback — Gemini API unavailable]")
            },
            zoneAssignments = linkedMapOf(
                "alpha" to "Rapid triage sweep for RED cases first.",
                "bravo" to "Stabilize YELLOW cases and prepare evacuation.",
                "charlie" to "Search secondary structures for unreported victims."
            ),
            estimatedCasualties = packets.size + (auto / 2),
            criticalAlert = if (auto >= 3 || red >= 3)
                "Potential structural collapse cluster detected. Prioritize heavy rescue support."
            else null
        )
    }

    companion object {
        private const val TAG = "DispatchAgent"
    }
}
