package com.omnimesh.app.ml

import omnimesh.command1.data.TriagePacket
import omnimesh.command1.ml.MotionSignal
import omnimesh.command1.utils.DeviceUtils
import android.content.Context
import java.util.UUID
import kotlin.math.max
import kotlin.math.min

/**
 * Fuses motion collapse detection with optional vision triage for auto-SOS packets.
 * Vision runs via [VisionClassifier.classify] on the latest capture path, or neutral when null.
 */
class TriageFusionPipeline(
    private val visionClassifier: VisionClassifier
) {

    suspend fun buildCollapseAutoSosPacket(
        motion: MotionSignal,
        currentImagePath: String?,
        latitude: Double,
        longitude: Double,
        context: Context
    ): TriagePacket {
        val vision = visionClassifier.classify(currentImagePath)

        val sources = buildString {
            append("M")
            if (vision.signalCode.isNotEmpty()) append(vision.signalCode)
        }

        val injury = buildString {
            append("collapse_auto_detected")
            if (vision.signalCode == "V" && vision.classification != "UNKNOWN") {
                append("|vision:")
                append(vision.classification)
            }
        }

        val visionTop = vision.probabilities.maxOrNull() ?: 0f
        val fusedConfidence = min(
            0.99f,
            max(
                motion.confidence,
                motion.confidence * 0.65f + vision.confidence * visionTop * 0.35f
            )
        )

        return TriagePacket(
            id = UUID.randomUUID().toString().take(8),
            urgency = "RED",
            injury = injury,
            loc = "auto_inertial_sos",
            lat = latitude,
            lon = longitude,
            ts = System.currentTimeMillis(),
            confidence = fusedConfidence,
            signalSources = sources,
            isAutoGenerated = true,
            originDeviceId = DeviceUtils.getDeviceId(context)
        )
    }
}
