import {
  collection,
  doc,
  getDocs,
  query,
  where,
  writeBatch,
} from "firebase/firestore";
import { db } from "./firebase";

const CENTER = { lat: 37.7749, lon: -122.4194 };

const RED_INJURIES = ["severe bleeding", "crush injury", "unconscious", "spinal trauma"];
const YELLOW_INJURIES = ["fractured arm", "smoke inhalation", "moderate burns"];
const GREEN_INJURIES = ["minor cuts", "dehydration", "anxiety"];

const BATCH_MAX = 500;

function pickUrgency() {
  const r = Math.random();
  if (r < 0.25) return "RED";
  if (r < 0.6) return "YELLOW";
  return "GREEN";
}

function pickInjury(urgency) {
  const list =
    urgency === "RED" ? RED_INJURIES : urgency === "YELLOW" ? YELLOW_INJURIES : GREEN_INJURIES;
  return list[Math.floor(Math.random() * list.length)];
}

function randConfidence() {
  return Number((0.65 + Math.random() * (0.99 - 0.65)).toFixed(3));
}

function jitterCoord() {
  const dLat = (Math.random() - 0.5) * 0.045;
  const dLon = (Math.random() - 0.5) * 0.045;
  return {
    lat: CENTER.lat + dLat,
    lon: CENTER.lon + dLon,
  };
}

/**
 * Seed Firestore `packets` with realistic triage rows (isTestData: true).
 * Uses batched writes (500 ops max per batch). Document IDs are auto-generated (unique).
 */
export async function seedTestPackets(count = 10) {
  if (!db) throw new Error("Firestore is not configured");

  const baseTs = Date.now();
  let written = 0;
  let timeIndex = 0;

  while (written < count) {
    const chunkSize = Math.min(BATCH_MAX, count - written);
    const batch = writeBatch(db);

    for (let i = 0; i < chunkSize; i++) {
      const ref = doc(collection(db, "packets"));
      const urgency = pickUrgency();
      const randomOffset = Math.floor(Math.random() * 12_000);
      const ts = baseTs - timeIndex * 750 - randomOffset;
      timeIndex += 1;
      const { lat, lon } = jitterCoord();

      batch.set(ref, {
        id: ref.id,
        urgency,
        injury: pickInjury(urgency),
        lat,
        lon,
        ts,
        confidence: randConfidence(),
        synced: true,
        isAutoGenerated: false,
        signalSources: ["M", "V"],
        isTestData: true,
      });
    }

    await batch.commit();
    written += chunkSize;
  }

  console.log("Seeded packets:", count);
}

/**
 * Delete all documents in `packets` where isTestData === true (batched).
 */
export async function clearTestPackets() {
  if (!db) throw new Error("Firestore is not configured");

  const q = query(collection(db, "packets"), where("isTestData", "==", true));
  const snap = await getDocs(q);
  const docs = snap.docs;

  if (docs.length === 0) {
    console.log("Cleared test packets");
    return;
  }

  for (let i = 0; i < docs.length; i += BATCH_MAX) {
    const batch = writeBatch(db);
    docs.slice(i, i + BATCH_MAX).forEach((d) => batch.delete(d.ref));
    await batch.commit();
  }

  console.log("Cleared test packets");
}
